# Generated by Django 4.1.5 on 2023-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_task_completed_task_due_date_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('done', 'Done'), ('overdue', 'Overdue')], max_length=200),
        ),
    ]
