# Generated by Django 4.1.5 on 2023-01-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='task_app.person'),
            preserve_default=False,
        ),
    ]
